name: eris-pages GH Actions

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: linting src directory
        run: npm i && npm run eslint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: building src dir
        run: npm i && npm run build
